### ISSUE TITLE
Run as web notwork

### ISSUE THREAD

**Issue by salahatwa** [digimezzo/knowte-electron#78]
I received following error during try to run application as web , it's seem not compatible with web

`>> ng ng:serve:web`
ERROR in ./node_modules/graceful-fs/polyfills.js
Module not found: Error: Can't resolve 'constants' in 'path/knowte-electron-master/node_modules/graceful-fs'

**Comment by digimezzo** [comment]
It was not designed to work as a website. There are multiple Electron dependencies, which won't allow launching it as a website.

**Comment by salahatwa** [comment]
we already remove all electron and it's working fine as web now
